# Read the Docs configuration file for HyGCS
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Build documentation in the docs/ directory
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Python version and requirements
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Install Python dependencies
python:
  install:
    - requirements: docs/requirements-docs.txt
    - method: pip
      path: .
